import { useEffect, useState } from 'react'
import { collection, doc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore'
import { db } from '../firebase'
import { Button, EmptyState, Field, Modal, Toast, useToast } from './ui'
import MapManager from '../MapManager'
const blank = { name: '', delivery_fee_base: 0, surge_multiplier: 1, is_active: true, is_accepting_orders: true }
export default function ZonesPage() {
  const [items, setItems] = useState([]); const [vendors, setVendors] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [draftPoints, setDraftPoints] = useState([]); const { toast, notify } = useToast()
  useEffect(() => { let active = true; getDocs(collection(db, 'zones')).then(s => { if (active) setItems(s.docs.map(d => ({ id: d.id, ...d.data() }))) }).catch(() => { if (active) notify('تعذر تحميل المناطق', 'error') }); return () => { active = false } }, [notify])
  useEffect(() => { let active = true; getDocs(collection(db, 'vendors')).then(s => { if (active) setVendors(s.docs.map(d => ({ id: d.id, ...d.data() }))) }); return () => { active = false } }, [])
  const save = async e => { e.preventDefault(); if (!form.name.trim()) return notify('أدخل اسم المنطقة', 'error'); setBusy(true); try { const id = editing || `zone-${Date.now()}`; await setDoc(doc(db, 'zones', id), { ...form, name: form.name.trim(), delivery_fee_base: Number(form.delivery_fee_base), surge_multiplier: Number(form.surge_multiplier), updated_at: serverTimestamp(), ...(editing ? {} : { created_at: serverTimestamp() }) }, { merge: true }); setEditing(id); notify('تم حفظ بيانات المنطقة، ارسم حدودها على الخريطة'); } catch { notify('فشل حفظ المنطقة', 'error') } finally { setBusy(false) } }
  const saveMappedZone = async (zoneId, polygon) => { if (!zoneId || polygon.length < 3) return notify('ارسم ثلاثة نقاط على الأقل', 'error'); try { await setDoc(doc(db, 'zones_geo', zoneId), { zone_id: zoneId, name: form.name, polygon: polygon.map(([lat, lng]) => ({ lat, lng })), is_active: true, updated_at: serverTimestamp() }, { merge: true }); notify('تم حفظ حدود المنطقة بدقة'); setOpen(false); setEditing(null); setForm(blank); setDraftPoints([]) } catch { notify('تعذر حفظ حدود المنطقة', 'error') } }
  const startAdd = () => { setForm(blank); setEditing(null); setDraftPoints([]); setOpen(true) }
  return <><section className="page-heading"><div><p className="eyebrow">CONFIGURATION / ZONES</p><h1>مناطق التوصيل</h1><p>أدخل الاسم ثم ارسم الحدود مباشرة على الخريطة.</p></div><Button onClick={startAdd}>+ إضافة منطقة</Button></section><section className="data-card"><table><thead><tr><th>المنطقة</th><th>الرسم الأساسي</th><th>المضاعف</th><th>الاستقبال</th><th /></tr></thead><tbody>{items.map(z => <tr key={z.id}><td><strong>{z.name}</strong><small>{z.id}</small></td><td>{z.delivery_fee_base || 0} ل.س</td><td>×{z.surge_multiplier || 1}</td><td><span className={`badge ${z.is_accepting_orders === false ? 'muted' : 'green'}`}>{z.is_accepting_orders === false ? 'متوقف' : 'يستقبل'}</span></td><td><Button variant="ghost" onClick={() => { setForm({ ...blank, ...z }); setEditing(z.id); setDraftPoints([]); setOpen(true) }}>تعديل</Button></td></tr>)}</tbody></table>{!items.length && <EmptyState>لم تتم إضافة مناطق بعد.</EmptyState>}</section>{open && <Modal title={editing ? 'تعديل منطقة وحدودها' : 'إضافة منطقة'} onClose={() => setOpen(false)}><form className="form-grid" onSubmit={save}><Field label="اسم المنطقة" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /><Field label="الرسم الأساسي" type="number" min="0" value={form.delivery_fee_base} onChange={e => setForm({ ...form, delivery_fee_base: e.target.value })} /><Field label="مضاعف الرسم" type="number" min="0" step="0.1" value={form.surge_multiplier} onChange={e => setForm({ ...form, surge_multiplier: e.target.value })} /><label className="check-field"><input type="checkbox" checked={form.is_active} onChange={e => setForm({ ...form, is_active: e.target.checked })} /> المنطقة نشطة</label><label className="check-field"><input type="checkbox" checked={form.is_accepting_orders} onChange={e => setForm({ ...form, is_accepting_orders: e.target.checked })} /> تستقبل طلبات</label><div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>إلغاء</Button><Button type="submit" busy={busy}>حفظ الاسم والمتابعة للخريطة</Button></div></form>{editing && <MapManager zones={items} vendors={vendors} draftZoneId={editing} draftZonePoints={draftPoints} onDraftZonePoints={setDraftPoints} onSaveZone={saveMappedZone} onSaveVendorLocation={() => {}} />}</Modal>}<Toast toast={toast} /></>
}
