import { Component, useEffect, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { collection, doc, getDoc, onSnapshot } from 'firebase/firestore'
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth'
import { auth, db, firebaseConfigError, firebaseInitError, hasFirebaseConfig } from './firebase'
import { Button, Field } from './components/ui'
import VendorsPage from './components/VendorsPage'
import ZonesPage from './components/ZonesPage'
import { BankTransfersPage, CouponsPage, CouriersPage, OrdersPage, SettingsPage, SettlementsPage, SupportTicketsPage } from './components/OperationsPages'
import MasterSettingsPage from './components/MasterSettingsPage'
import ChangeRequestsPage from './components/ChangeRequestsPage'
import './App.css'

const query = new URLSearchParams(window.location.search)
const routerOnly = query.get('routerOnly') === '1'
const pageTest = query.get('pageTest')
const pageSet = pageTest ? pageTest.split(',').map(item => item.trim()).filter(Boolean) : []
const showPage = name => pageSet.length === 0 || pageSet.includes(name)

class PageErrorBoundary extends Component {
  constructor(props) { super(props); this.state = { error: null } }
  static getDerivedStateFromError(error) { return { error } }
  componentDidCatch(error) { console.error('Admin page error:', error) }
  render() {
    if (!this.state.error) return this.props.children
    return <section className="data-card page-error" dir="rtl"><p className="eyebrow">ADMIN / RECOVERY</p><h1>تعذر تحميل هذه الصفحة</h1><p>حدث خطأ داخل الصفحة الحالية، لكن يمكنك استخدام القائمة للانتقال إلى قسم آخر.</p><button className="ui-button" type="button" onClick={() => this.setState({ error: null })}>إعادة المحاولة</button><div className="config-diagnostic">{this.state.error.message || String(this.state.error)}</div></section>
  }
}

function LoginScreen({ configError = false }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{await signInWithEmailAndPassword(auth,email.trim(),password)}catch(err){setError(err.code==='auth/invalid-credential'||err.code==='auth/user-not-found'||err.code==='auth/wrong-password'?'البريد الإلكتروني أو كلمة المرور غير صحيحة.':'تعذر تسجيل الدخول. تحقق من Firebase وحساب الأدمن.')}finally{setBusy(false)}}
  return <main dir="rtl" className="auth-shell"><section className="auth-card"><p className="eyebrow">SYRIA DELIVERY / ADMIN</p><h1>تسجيل دخول الأدمن</h1><p className="auth-description">أدخل حسابًا يملك دور <b>super_admin</b>.</p>{configError&&<><div className="error-message">لم يتم تشغيل اتصال Firebase. أصلح إعدادات البيئة ثم أعد تشغيل Vite.</div><div className="config-diagnostic">{firebaseConfigError||firebaseInitError||'auth أو Firestore غير متاحين'}</div></>}<form onSubmit={submit} className="auth-form"><Field label="البريد الإلكتروني" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required disabled={configError}/><Field label="كلمة المرور" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required disabled={configError}/>{error&&<div className="error-message">{error}</div>}<Button type="submit" busy={busy} disabled={configError}>دخول آمن</Button></form></section></main>
}
function DiagnosticPage({ title }) { return <section className="data-card welcome-panel"><p className="eyebrow">ROUTER DIAGNOSTIC</p><h1>{title}</h1><p>هذه صفحة اختبار ثابتة بلا Firebase أو Firestore أو خرائط. إذا استمر التعليق هنا فالمشكلة في Router أو CSS أو المتصفح.</p></section> }
function AccessDenied({ user }) { return <main dir="rtl" className="auth-shell"><section className="auth-card"><p className="eyebrow">SYRIA DELIVERY / ACCESS</p><h1>لا يوجد تصريح دخول</h1><p className="auth-description">الحساب <b>{user.email}</b> لا يملك دور <b>super_admin</b>.</p><Button onClick={()=>signOut(auth)}>تسجيل الخروج</Button></section></main> }
function Overview({ user }) { const [stats,setStats]=useState({vendors:0,orders:0,zones:0,couriers:0});useEffect(()=>{const un=[];for(const [key,name] of Object.entries({vendors:'vendors',orders:'orders',zones:'zones',couriers:'couriers'}))un.push(onSnapshot(collection(db,name),s=>setStats(x=>({...x,[key]:s.size}))));return()=>un.forEach(fn=>fn())},[]);return <><section className="page-heading"><div><p className="eyebrow">REAL-TIME OPERATIONS</p><h1>مركز العمليات</h1><p>مرحبًا {user.email}. تابع مؤشرات النظام من مكان واحد.</p></div></section><section className="metric-grid">{[['vendors','المزودون'],['orders','الطلبات'],['zones','المناطق'],['couriers','المندوبون']].map(([key,label])=><article className="metric-card" key={key}><span>{label}</span><strong>{stats[key]}</strong><small>قراءة لحظية من Firestore</small></article>)}</section><section className="data-card welcome-panel"><h2>ابدأ بإعداد النظام</h2><p>أضف المناطق والمزودين، ثم أنشئ حسابات التاجر والمندوب من Firebase Authentication. جميع الإعدادات التشغيلية لاحقًا قابلة للتعديل من القائمة الجانبية.</p></section></> }
const nav=[['/','الرئيسية','⌂'],['/vendors','المزودون','▦'],['/zones','المناطق','⌖'],['/orders','الطلبات','◌'],['/couriers','المندوبون','♙'],['/coupons','الكوبونات','◇'],['/settlements','الورديات والتسويات','▤'],['/bank-transfers','التحويلات البنكية','⇄'],['/support','الدعم والشكاوى','?'],['/change-requests','طلبات الفكة','↔'],['/settings','الإعدادات','⚙'],['/master-settings','التحكم الشامل','◆']]
function Layout({ user }) { const location=useLocation();const zones=useZones();const title=nav.find(([path])=>path===location.pathname)?.[1]||'لوحة التحكم';return <div className="dashboard-shell" dir="rtl"><aside className="sidebar"><div className="brand"><span className="brand-mark">SD</span><div><strong>Syria Delivery</strong><small>Operations Center</small></div></div><nav aria-label="التنقل الرئيسي">{nav.map(([path,label,icon])=><NavLink key={path} to={path} end={path==='/' } onClick={() => console.info('[admin-nav]', path, new Date().toISOString())} className={({isActive})=>isActive?'active':''}><span className="nav-icon" aria-hidden="true">{icon}</span>{label}</NavLink>)}</nav><div className="sidebar-footer"><span className="online-dot"/> متصل بـ Firebase</div></aside><div className="dashboard-main"><header className="dashboard-topbar"><div><span className="breadcrumb">SYRIA DELIVERY / ADMIN</span><h2>{title}</h2></div><div className="user-menu"><span>{user.email}</span><button className="topbar-logout" type="button" onClick={()=>signOut(auth)}>خروج</button></div></header><main className="page-content"><PageErrorBoundary><Routes><Route path="/" element={routerOnly || !showPage('overview') ? <DiagnosticPage title="الرئيسية"/> : <Overview user={user}/>}/> <Route path="/vendors" element={routerOnly || !showPage('vendors') ? <DiagnosticPage title="المزودون"/> : <VendorsPage zones={zones}/>}/> <Route path="/zones" element={routerOnly || !showPage('zones') ? <DiagnosticPage title="المناطق"/> : <ZonesPage/>}/> <Route path="/orders" element={routerOnly || !showPage('orders') ? <DiagnosticPage title="الطلبات"/> : <OrdersPage/>}/> <Route path="/couriers" element={routerOnly || !showPage('couriers') ? <DiagnosticPage title="المندوبون"/> : <CouriersPage/>}/> <Route path="/coupons" element={routerOnly || !showPage('coupons') ? <DiagnosticPage title="الكوبونات"/> : <CouponsPage/>}/> <Route path="/settlements" element={routerOnly || !showPage('settlements') ? <DiagnosticPage title="التسويات"/> : <SettlementsPage/>}/> <Route path="/bank-transfers" element={routerOnly || !showPage('bank-transfers') ? <DiagnosticPage title="التحويلات البنكية"/> : <BankTransfersPage/>}/> <Route path="/support" element={routerOnly || !showPage('support') ? <DiagnosticPage title="الدعم والشكاوى"/> : <SupportTicketsPage/>}/> <Route path="/change-requests" element={routerOnly || !showPage('change-requests') ? <DiagnosticPage title="طلبات الفكة"/> : <ChangeRequestsPage/>}/> <Route path="/settings" element={routerOnly || !showPage('settings') ? <DiagnosticPage title="الإعدادات"/> : <SettingsPage/>}/> <Route path="/master-settings" element={routerOnly || !showPage('master-settings') ? <DiagnosticPage title="التحكم الشامل"/> : <MasterSettingsPage/>}/> <Route path="*" element={<Navigate to="/" replace/>}/></Routes></PageErrorBoundary></main></div></div> }
function useZones(){const [zones,setZones]=useState([]);useEffect(()=>{if(routerOnly)return undefined;return onSnapshot(collection(db,'zones'),s=>setZones(s.docs.map(d=>({id:d.id,...d.data()}))))},[]);return zones}
function App(){const [user,setUser]=useState(undefined);const [authorized,setAuthorized]=useState(false);const [checking,setChecking]=useState(false);useEffect(()=>{if(!auth||!db){setUser(null);return undefined}let active=true;let request=0;const unsubscribe=onAuthStateChanged(auth,async next=>{const current=++request;if(!active)return;setUser(next);setAuthorized(false);if(!next){setChecking(false);return}setChecking(true);try{const profile=await Promise.race([getDoc(doc(db,'users',next.uid)),new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),5000))]);if(active&&current===request)setAuthorized(profile.exists()&&profile.data().role==='super_admin')}catch{if(active&&current===request)setAuthorized(false)}finally{if(active&&current===request)setChecking(false)}});return()=>{active=false;unsubscribe()}},[]);if(!hasFirebaseConfig||!auth||!db)return <LoginScreen configError/>;if(user===undefined||checking)return <main dir="rtl" className="auth-shell"><section className="auth-card"><p>جارٍ التحقق من جلسة الأدمن…</p></section></main>;if(!user)return <LoginScreen/>;if(!authorized)return <AccessDenied user={user}/>;return <Layout user={user}/>}
export default App
