import { useEffect, useState } from 'react'
import { MapContainer, TileLayer, Marker, Polygon, CircleMarker, useMap, useMapEvents } from 'react-leaflet'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'

const mapsDisabled = new URLSearchParams(window.location.search).get('noMap') === '1'
const markerIcon = new L.Icon({ iconUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png', shadowUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png', iconSize: [25, 41], iconAnchor: [12, 41] })
function MapInteractions({ onClick, onContext }) { useMapEvents({ click: e => onClick([e.latlng.lat, e.latlng.lng]), contextmenu: e => onContext({ point: [e.latlng.lat, e.latlng.lng], x: e.containerPoint.x, y: e.containerPoint.y }) }); return null }
function Recenter({ point }) { const map = useMap(); useEffect(() => { if (point) map.flyTo(point, 15) }, [map, point]); return null }
async function searchPlace(query) { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&accept-language=ar&q=${encodeURIComponent(query)}`, { headers: { 'Accept-Language': 'ar' } }); return response.json() }
export function GeoSearch({ onSelect, placeholder = 'ابحث باسم مكان أو عنوان…' }) { const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [busy, setBusy] = useState(false); const submit = async e => { e.preventDefault(); if (!query.trim()) return; setBusy(true); try { setResults(await searchPlace(query.trim())) } catch { setResults([]) } finally { setBusy(false) } }; return <div className="geo-search"><form onSubmit={submit}><input value={query} onChange={e => setQuery(e.target.value)} placeholder={placeholder} /><button className="ui-button secondary" disabled={busy}>{busy ? 'بحث…' : 'بحث جغرافي'}</button></form>{results.length > 0 && <div className="geo-results">{results.map(result => <button type="button" key={result.place_id} onClick={() => { onSelect([Number(result.lat), Number(result.lon)]); setResults([]); setQuery(result.display_name) }}>{result.display_name}</button>)}</div>}</div> }
export default function MapManager({ vendors = [], zones = [], onSaveZone, onSaveVendorLocation, draftZoneId = '', draftZonePoints = [], onDraftZonePoints, search = true, onQuickAction }) {
  const [points, setPoints] = useState(draftZonePoints); const [selectedVendor, setSelectedVendor] = useState(''); const [center, setCenter] = useState([33.5138, 36.2765]); const [menu, setMenu] = useState(null)
  useEffect(() => setPoints(draftZonePoints), [draftZonePoints])
  const updatePoint = (index, point) => { const next = points.map((item, i) => i === index ? point : item); setPoints(next); onDraftZonePoints?.(next) }
  const click = point => { if (selectedVendor) onSaveVendorLocation?.(selectedVendor, point); else { const next = [...points, point]; setPoints(next); onDraftZonePoints?.(next) } }
  const quickAction = action => { if (!menu) return; const point = menu.point; if (action === 'vendor' && onSaveVendorLocation) onSaveVendorLocation(selectedVendor || vendors[0]?.id, point); if (action === 'boundary') click(point); onQuickAction?.(action, point); setMenu(null) }
  const save = () => onSaveZone?.(draftZoneId || null, points)
  if (mapsDisabled) return <section className="panel map-panel map-disabled"><div className="panel-heading"><div><p className="eyebrow">DIAGNOSTIC MODE</p><h2>الخريطة معطّلة للاختبار</h2></div></div><p className="map-help">تم تفعيل noMap=1. اختبر التنقل الآن؛ إذا اختفى التعليق فالمشكلة داخل Leaflet.</p></section>
  return <section className="panel map-panel"><div className="panel-heading"><div><p className="eyebrow">المناطق والمواقع</p><h2>خريطة العمليات</h2></div>{onSaveZone && <button className="ui-button secondary" onClick={save}>حفظ حدود المنطقة</button>}</div>{search && <GeoSearch onSelect={setCenter} />}<p className="map-help">النقر الأيسر يضيف نقطة، والنقر بالزر الأيمن يفتح إجراءات سريعة. اسحب العلامات لتعديل المواقع.</p><div className="map-toolbar">{onSaveZone && <button className="ui-button secondary" onClick={() => { setPoints([]); onDraftZonePoints?.([]) }}>مسح النقاط</button>}<select value={selectedVendor} onChange={e => setSelectedVendor(e.target.value)}><option value="">تحديد يدوي للحدود</option>{vendors.map(v => <option key={v.id} value={v.id}>موقع: {v.name}</option>)}</select></div><div className="map-frame"><MapContainer center={center} zoom={12} style={{ height: 390, width: '100%', borderRadius: 14 }}><Recenter point={center} /><TileLayer attribution="&copy; OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><MapInteractions onClick={point => { setMenu(null); click(point) }} onContext={setMenu} />{points.map((point, index) => <Marker key={`draft-${index}`} position={point} draggable eventHandlers={{ dragend: e => { const p = e.target.getLatLng(); updatePoint(index, [p.lat, p.lng]) } }} />)}{points.length > 2 && <Polygon positions={points} color="#2f8b5d" />}{zones.map(z => z.polygon && <Polygon key={z.id} positions={z.polygon.map(p => [p.lat, p.lng])} color="#d8a55b" />)}{vendors.map(v => v.location && <Marker key={v.id} position={[v.location.latitude, v.location.longitude]} icon={markerIcon} draggable eventHandlers={{ dragend: e => { const p = e.target.getLatLng(); onSaveVendorLocation?.(v.id, [p.lat, p.lng]) } }} />)}</MapContainer>{menu && <div className="map-context-menu" style={{ left: menu.x, top: menu.y }}><strong>إجراء سريع</strong><button onClick={() => quickAction('vendor')}>إضافة/تحديث مزود هنا</button><button onClick={() => quickAction('boundary')}>إضافة نقطة حدودية</button><button onClick={() => quickAction('courier')}>تعيين موقع مندوب</button><button className="close-context" onClick={() => setMenu(null)}>إغلاق</button></div>}</div></section>
}
