const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const functions = fs.readFileSync(path.join(root, 'functions', 'index.js'), 'utf8');
const errands = fs.readFileSync(path.join(root, 'functions', 'errands.js'), 'utf8');
const errandScreen = fs.readFileSync(path.join(root, 'customer_app', 'lib', 'screens', 'errand_screen.dart'), 'utf8');
const rules = fs.readFileSync(path.join(root, 'firestore.rules'), 'utf8');
const customer = fs.readFileSync(path.join(root, 'customer_app', 'lib', 'common.dart'), 'utf8');
const courier = fs.readFileSync(path.join(root, 'courier_app', 'lib', 'common.dart'), 'utf8');
const courierOrders = fs.readFileSync(path.join(root, 'courier_app', 'lib', 'screens', 'orders_screen.dart'), 'utf8');
const merchant = fs.readFileSync(path.join(root, 'merchant_app', 'lib', 'common.dart'), 'utf8');
const adminFirebase = fs.readFileSync(path.join(root, 'admin-dashboard', 'src', 'firebase.js'), 'utf8');
const masterSettings = fs.readFileSync(path.join(root, 'admin-dashboard', 'src', 'components', 'MasterSettingsPage.jsx'), 'utf8');
const adminSettings = fs.readFileSync(path.join(root, 'admin-dashboard', 'src', 'components', 'OperationsPages.jsx'), 'utf8');
const changeRequests = fs.readFileSync(path.join(root, 'admin-dashboard', 'src', 'components', 'ChangeRequestsPage.jsx'), 'utf8');
const envSafety = fs.readFileSync(path.join(root, 'scripts', 'test-env-safety.js'), 'utf8');

function assert(condition, message) {
  if (!condition) throw new Error(`SECURITY CONTRACT FAILED: ${message}`);
}

assert(/if \(nextStatus === 'delivered'\) throw/.test(functions), 'direct delivered transition must be rejected');
assert(/exports\.completeDelivery/.test(functions), 'OTP delivery callable must exist');
assert(/Number\.isInteger\(quantity\)/.test(functions), 'order quantity must be integer validated');
assert(/normalizePoint\(address\.location\)/.test(functions) && /pickZone\(deliveryPoint, zones\)/.test(functions), 'delivery location must be valid and inside the requested zone');
assert(/userSnap\.data\(\)\?\.role !== 'customer'/.test(functions), 'createOrder must reject non-customer roles');
assert(/exports\.cancelOrder/.test(functions), 'refund-aware cancellation callable must exist');
assert(/userSnap\.data\(\)\?\.role !== 'customer'/.test(functions), 'cancelOrder must reject non-customer roles');
assert(/customerReferralDefaults/.test(functions), 'customer referral initialization must use the balance-preserving helper');
assert(/error\?\.code === 'invalid-argument'/.test(functions) && /new HttpsError\('internal'/.test(functions), 'unexpected payload-guard errors must not be exposed as invalid-argument');
assert(/exports\.createErrand|createErrand = onCall/.test(errands), 'errand callable must exist');
assert(!/exports\.changeToWallet/.test(functions) && !/changeToWallet = onCall/.test(errands), 'old auto-credit changeToWallet must not exist');
assert(/buildErrandFunctions/.test(functions), 'index.js must load errands.js');
assert(!/data\?\.(delivery_fee|zone_id)/.test(errands), 'errand fee and zone must never be read from the client');
assert(/zones_geo/.test(errands) && /pickZone/.test(errands), 'errand zone must be derived from zones_geo polygons');
assert(/expected_fee/.test(errands), 'errand creation must require the confirmed quote');
assert(/idempotency_key/.test(errands), 'errand creation must be idempotent');
const requestBlock = errands.slice(errands.indexOf('const requestChangeToWallet'), errands.indexOf('const reviewChangeRequest'));
assert(requestBlock.length > 100 && !/wallet_balance/.test(requestBlock), 'requesting change must never credit the wallet');
assert(/change_requests/.test(requestBlock) && /order\.status !== 'delivered'/.test(requestBlock), 'change request must require a delivered order');
const reviewBlock = errands.slice(errands.indexOf('const reviewChangeRequest'));
assert(/requireRole\(adminId, \['super_admin'\]\)/.test(reviewBlock) && /wallet_balance/.test(reviewBlock), 'only admins may credit the wallet after review');
assert(/match \/change_requests\/{orderId}[^\n]*allow write: if false;/.test(rules), 'change_requests must be callable-only');
assert(!/['"]delivery_fee['"]\s*:/.test(errandScreen) && !/['"]zone_id['"]\s*:/.test(errandScreen), 'customer errand screen must not send fee or zone');
assert(/maxChange/.test(functions), 'createOrder must cap the cash change amount');
const smokeOrder = fs.readFileSync(path.join(root, 'scripts', 'smoke-order.js'), 'utf8');
assert(/missingLocation/.test(smokeOrder) && /outsideZone/.test(smokeOrder) && /invalidValues/.test(smokeOrder) && /boundary_inclusive/.test(smokeOrder) && /cancel_unauthenticated_rejected/.test(smokeOrder) && /cancel_non_customer_rejected/.test(smokeOrder) && /cancel_invalid_id_rejected/.test(smokeOrder) && /cancel_missing_order_rejected/.test(smokeOrder) && /direct_write_denied/.test(smokeOrder) && /other_customer_read_denied/.test(smokeOrder) && /unfiltered_order_list_denied/.test(smokeOrder) && /sensitive_updates_denied/.test(smokeOrder) && /customer_cancel_other_customer_denied/.test(smokeOrder) && /customer_cancel_direct_write_denied/.test(smokeOrder) && /customer_cancel_callable_allowed/.test(smokeOrder) && /customer_cancel_wrong_status_denied/.test(smokeOrder) && /advancedStatusChecks/.test(smokeOrder) && /hybridRefundCheck/.test(smokeOrder) && /cancelCallableUrl/.test(smokeOrder) && /payment_method/.test(smokeOrder) && /delivery_address/.test(smokeOrder) && /assertCustomerOrderQueryWorks/.test(smokeOrder) && /concurrent_idempotency/.test(smokeOrder) && /Array\.from\(\{length: 20\}/.test(smokeOrder) && /Promise\.all/.test(smokeOrder) && /INVALID_ARGUMENT/.test(smokeOrder), 'createOrder and cancelOrder smoke tests must cover invalid, list/read/write security, callable-only cancellation, advanced statuses, hybrid refunds, scoped reads, 20-way concurrency, boundary, and valid locations');
assert(/__smoke_unknown/.test(smokeOrder) && /atomicity injection blocked on staging/.test(smokeOrder) && /smoke_fields_rejected/.test(smokeOrder), 'Smoke must verify smoke-field rejection locally and on staging');
assert(/tx\.create\(orderRef/.test(functions) && /tx\.create\(idempotencyRef/.test(functions), 'order and idempotency marker must be committed in one transaction');
const atomicityGuard = fs.readFileSync(path.join(root, 'functions', 'atomicity-guard.js'), 'utf8');
const atomicityTest = fs.readFileSync(path.join(root, 'scripts', 'atomicity-guard.test.js'), 'utf8');
assert(/prepareCreateOrderPayload/.test(functions) && /functionsEmulator/.test(atomicityGuard) && /delete payload\.__smoke_fail_after_order_write/.test(atomicityGuard) && /functionsEmulator: false/.test(atomicityTest) && /shouldInjectFailure/.test(atomicityTest), 'partial-write injection must be emulator-only, rejected outside it, and removed before order validation and idempotency hashing');
const referralProfile = fs.readFileSync(path.join(root, 'functions', 'referral-profile.js'), 'utf8');
const referralTest = fs.readFileSync(path.join(root, 'scripts', 'referral-profile.test.js'), 'utf8');
assert(/customerReferralDefaults/.test(functions) && /wallet_balance/.test(referralProfile) && /loyalty_points/.test(referralProfile) && /deepStrictEqual\(secondPresetMerged, firstPresetMerged/.test(referralTest) && /missing referral fields/.test(referralTest), 'referral initialization must preserve balances and be idempotent with missing-field defaults');
assert(/SMOKE_FAIL_AFTER_ORDER_WRITE/.test(envSafety) && /\.env\.\*/.test(envSafety) && /\.env\.example/.test(envSafety), 'smoke injection env must be protected from tracked non-local env files');
assert(/max_change_amount: \{type: 'number'/.test(functions) && /max_change_amount: Number\(config\.max_change_amount\) \|\| 0/.test(adminSettings), 'max_change_amount must be allowlisted, fallback-safe, and published from admin settings');
assert(/where\('status', '==', 'pending'\)/.test(changeRequests) && /orderBy\('requested_at', 'desc'\)/.test(changeRequests) && /orderBy\('reviewed_at', 'desc'\)/.test(changeRequests) && /limit\(100\)/.test(changeRequests) && /limit\(50\)/.test(changeRequests), 'change request dashboard must bound and order pending and reviewed reads');
assert(/window\.confirm/.test(changeRequests) && /courier_claimed_amount/.test(changeRequests), 'change request approval must confirm and show claimed amount');
assert(/messaging\/registration-token-not-registered/.test(functions), 'notification failure must not abort accounting');
assert(/request\.resource\.data\.role == 'customer'/.test(rules), 'self-created users must be customers only');
assert(/request\.resource\.data\.keys\(\)\.hasOnly/.test(rules), 'user creation fields must be allowlisted');
assert(/match \/public_vendors\/{vendorId}/.test(rules), 'public vendor projection rule must exist');
assert(/match \/system_config\/{configId} \{ allow read: if admin\(\);/.test(rules) && /match \/public_config\/{configId} \{ allow read: if configId == 'main';/.test(rules), 'private config must be admin-only and public projection limited to main');
assert(/allow read: if resource\.data\.is_available == true \|\| admin\(\) \|\| vendorOwner\(vendorId\)/.test(rules), 'available products must be browsable by guests');
assert(/match \/wallet_topups\/{topupId} \{ allow read: if signedIn\(\) && resource\.data\.customer_id == request\.auth\.uid; allow create: if false;/.test(rules), 'wallet topups must be callable-only');
assert(/match \/ratings\/{ratingId}/.test(rules) && /allow create, update, delete: if false/.test(rules) && /exports\.submitRating/.test(functions), 'ratings must be written only through the validated server callable');
assert(/collection\('public_vendors'\)/.test(customer), 'customer must read sanitized public vendor catalog');
assert(!/defaultValue: true/.test(customer.match(/const useFirebaseEmulators[\s\S]{0,160}/)?.[0] || ''), 'production must not default to Firebase emulators');
assert(/instanceFor\(region: 'europe-west1'\)/.test(customer) && /instanceFor\(region: 'europe-west1'\)/.test(courier) && /instanceFor\(region: 'europe-west1'\)/.test(merchant), 'Flutter clients must target the deployed europe-west1 Functions region');
assert(!/FirebaseFunctions\.instance\.httpsCallable/.test(customer + courierOrders) && /requestChangeToWallet/.test(courierOrders) && !/httpsCallable\('changeToWallet'/.test(courierOrders), 'clients must use the current callable names and regional Functions client');
assert(/getFunctions\(app, 'europe-west1'\)/.test(adminFirebase), 'admin dashboard must target the deployed europe-west1 Functions region');
assert(/exports\.publishSystemConfig/.test(functions) && /httpsCallable\(functions, 'publishSystemConfig'\)/.test(masterSettings), 'master settings must publish through the validated callable');
assert(!/setDoc\(doc\(db, 'system_config'/.test(masterSettings) && !/setDoc\(doc\(collection\(db, 'audit_logs'/.test(masterSettings), 'master settings must not write config or audit records directly from the browser');
assert(/exports\.publishPaymentSettings/.test(functions) && /httpsCallable\(functions, 'publishPaymentSettings'\)/.test(masterSettings), 'payment settings must use a dedicated callable');
assert(/payment_config\/main/.test(functions) && /public_payment_config\/main/.test(functions) && /payment_config_revisions/.test(functions), 'payment settings must have private, public, and revision projections');
assert(/secret\|password\|token\|api/.test(functions) && /account_number\$/.test(functions), 'payment settings must reject secrets and full account numbers');
const publicConfigBlock = functions.slice(functions.indexOf('const PUBLIC_CONFIG_KEYS'), functions.indexOf('function buildPublicSystemConfig'));
assert(!/commission_by_zone|courier_min_withdrawal|merchant_min_withdrawal/.test(publicConfigBlock), 'internal commissions and withdrawal thresholds must not be public');
assert(/match \/payment_config\/{configId} \{ allow read: if admin\(\); allow write: if false; \}/.test(rules) && /match \/public_payment_config\/{configId} \{ allow read: if configId == 'main'; allow write: if false; \}/.test(rules), 'payment config rules must separate private and public documents');
const securityOps = fs.readFileSync(path.join(root, 'functions', 'security-ops.js'), 'utf8');
assert(/ENFORCE_APPCHECK/.test(securityOps) && /assertAppCheck/.test(functions), 'callables must have an environment-controlled App Check gate');
assert(/consumeQuota/.test(functions) && /security_rate_limits/.test(rules), 'support operations must use server-side quotas');
assert(/exports\.createSupportTicket/.test(functions) && /exports\.reviewSupportTicket/.test(functions) && /allow create, update, delete: if false/.test(rules), 'support tickets must be callable-only');
assert(/exports\.recordOperationalIncident/.test(functions) && /operational_incidents/.test(rules), 'operational incidents must be admin-readable and server-written');
console.log('Security contract tests passed.');
